### ISSUE TITLE
Implement life concept

### ISSUE THREAD

**Issue by bitbrain** [bitbrain/mindmazer#6]
A player has a number of given lifes. Initially the player receives a fixed amount of lifes. Whenever the player fails to complete the level he/she loses a life and respawns. As soon as the player has no lifes left he/she is GAME OVER.

In addition, advanced blocks may contain collectable life.

## Tasks

- [x] implement life concept into game stats
- [x] create life UI
- [x] implement proper game over logic. When the player dies and has at least 1 life left he/she respawns. Otherwise he/she is GAME OVER
- [x] track number of collected lifes/lost lifes (Achievements etc)
